name: dynamic_ui_executor
description: A powerful Flutter plugin for creating dynamic user interfaces from JSON or string definitions at runtime. Perfect for server-driven UI, A/B testing, and flexible app interfaces.
version: 1.0.0
homepage: https://github.com/yourusername/dynamic_ui_executor
repository: https://github.com/yourusername/dynamic_ui_executor
issue_tracker: https://github.com/yourusername/dynamic_ui_executor/issues
documentation: https://pub.dev/documentation/dynamic_ui_executor/latest/

topics:
  - dynamic-ui
  - server-driven-ui
  - json-ui
  - runtime-ui
  - flutter-widgets

# screenshots:
#   - description: 'Dynamic UI Dashboard Example'
#     path: screenshots/dashboard.png
#   - description: 'JSON to Flutter Widget Conversion'
#     path: screenshots/json-ui.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shariar99.dynamic_ui_executor
        pluginClass: DynamicUiExecutorPlugin
      ios:
        pluginClass: DynamicUiExecutorPlugin
      linux:
        pluginClass: DynamicUiExecutorPlugin
      macos:
        pluginClass: DynamicUiExecutorPlugin
      windows:
        pluginClass: DynamicUiExecutorPlugin
      web:
        pluginClass: DynamicUiExecutorPlugin
        fileName: dynamic_ui_executor_web.dart
